services:
  # Web Service - FastAPI Dashboard
  - type: web
    name: romanian-energy-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements-minimal.txt"
    startCommand: "python -m src.data.models && gunicorn -w 2 -k uvicorn.workers.UvicornWorker src.web.optimized_app:app --bind 0.0.0.0:$PORT"
    healthCheckPath: /health
    envVars:
      - key: RENDER
        value: "true"
      - key: ENTSOE_API_TOKEN
        value: "fe931761-163e-44ef-b106-854ad60e26ef"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PORT
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: romanian-energy-db
          property: connectionString

  # Background Worker - Data Collector
  - type: worker
    name: romanian-energy-collector
    env: python
    plan: free
    buildCommand: "pip install -r requirements-minimal.txt"
    startCommand: "python scheduled_collector.py"
    envVars:
      - key: RENDER
        value: "true"
      - key: ENTSOE_API_TOKEN
        value: "fe931761-163e-44ef-b106-854ad60e26ef"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        fromDatabase:
          name: romanian-energy-db
          property: connectionString

databases:
  # PostgreSQL Database
  - name: romanian-energy-db
    plan: free
    databaseName: romanian_energy_balancing
    user: romanian_energy_user
